apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-http-server-argo-declarative
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alio-CST-GitOps/Infrastructure
    targetRevision: development
    path: yaml-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-http-server-argo-declarative
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
